package org.jarling.v2.models.payments;

import lombok.Getter;

@Getter
public enum PaymentDescription {
    ACCEPTED("ACCEPTED"),
    QUALIFIED_ACCEPT_WITHIN_TWO_HOURS("QUALIFIED_ACCEPT_WITHIN_TWO_HOURS"),
    QUALIFIED_ACCEPT_UNSPECIFIED_DAY("QUALIFIED_ACCEPT_UNSPECIFIED_DAY"),
    QUALIFIED_ACCEPT_SAME_DAY("QUALIFIED_ACCEPT_SAME_DAY"),
    QUALIFIED_ACCEPT_NEXT_CALENDAR_DAY("QUALIFIED_ACCEPT_NEXT_CALENDAR_DAY"),
    QUALIFIED_ACCEPT_NEXT_WORKING_DAY("QUALIFIED_ACCEPT_NEXT_WORKING_DAY"),
    QUALIFIED_ACCEPT_AFTER_NEXT_WORKING_DAY("QUALIFIED_ACCEPT_AFTER_NEXT_WORKING_DAY"),
    DESTINATION_ACCOUNT_INVALID("DESTINATION_ACCOUNT_INVALID"),
    DESTINATION_ACCOUNT_NAME_MISMATCH("DESTINATION_ACCOUNT_NAME_MISMATCH"),
    REFERENCE_INFORMATION_INCORRECT("REFERENCE_INFORMATION_INCORRECT"),
    DESTINATION_ACCOUNT_UNAVAILABLE("DESTINATION_ACCOUNT_UNAVAILABLE");

    private final String value;

    PaymentDescription(String value) {
        this.value = value;
    }
}
