package org.jarling.v2.models.transactionfeed;

import lombok.Getter;

/**
 * The source of a transaction
 */
@Getter
public enum Source {
    CASH_DEPOSIT("CASH_DEPOSIT"),
    CASH_DEPOSIT_CHARGE("CASH_DEPOSIT_CHARGE"),
    CASH_WITHDRAWAL("CASH_WITHDRAWAL"),
    CASH_WITHDRAWAL_CHARGE("CASH_WITHDRAWAL_CHARGE"),
    CHAPS("CHAPS"),
    CHEQUE("CHEQUE"),
    CURRENCY_CLOUD("CURRENCY_CLOUD"),
    DIRECT_CREDIT("DIRECT_CREDIT"),
    DIRECT_DEBIT("DIRECT_DEBIT"),
    DIRECT_DEBIT_DISPUTE("DIRECT_DEBIT_DISPUTE"),
    INTERNAL_TRANSFER("INTERNAL_TRANSFER"),
    MASTER_CARD("MASTER_CARD"),
    MASTERCARD_MONEYSEND("MASTERCARD_MONEYSEND"),
    MASTERCARD_CHARGEBACK("MASTERCARD_CHARGEBACK"),
    FASTER_PAYMENTS_IN("FASTER_PAYMENTS_IN"),
    FASTER_PAYMENTS_OUT("FASTER_PAYMENTS_OUT"),
    FASTER_PAYMENTS_REVERSAL("FASTER_PAYMENTS_REVERSAL"),
    STRIPE_FUNDING("STRIPE_FUNDING"),
    INTEREST_PAYMENT("INTEREST_PAYMENT"),
    NOSTRO_DEPOSIT("NOSTRO_DEPOSIT"),
    OVERDRAFT("OVERDRAFT"),
    OVERDRAFT_INTEREST_WAIVED("OVERDRAFT_INTEREST_WAIVED"),
    FASTER_PAYMENTS_REFUND("FASTER_PAYMENTS_REFUND"),
    TRANSACTION_REFUND_SUSPENSE("TRANSACTION_REFUND_SUSPENSE"),
    EX_GRATIA_PAYMENT("EX_GRATIA_PAYMENT"),
    FRAUD_LOSS("FRAUD_LOSS"),
    FRAUD_LOSS_SUSPENSE("FRAUD_LOSS_SUSPENSE"),
    CHARITY_SUSPENSE("CHARITY_SUSPENSE"),
    STARLING_PAY_STRIPE("STARLING_PAY_STRIPE"),
    ON_US_PAY_ME("ON_US_PAY_ME"),
    LOAN_PRINCIPAL_PAYMENT("LOAN_PRINCIPAL_PAYMENT"),
    LOAN_REPAYMENT("LOAN_REPAYMENT"),
    LOAN_OVERPAYMENT("LOAN_OVERPAYMENT"),
    LOAN_LATE_PAYMENT("LOAN_LATE_PAYMENT"),
    SEPA_CREDIT_TRANSFER("SEPA_CREDIT_TRANSFER"),
    SEPA_DIRECT_DEBIT("SEPA_DIRECT_DEBIT"),
    TARGET2_CUSTOMER_PAYMENT("TARGET2_CUSTOMER_PAYMENT"),
    FX_TRANSFER("FX_TRANSFER"),
    BAD_DEBT_RECOVERY("BAD_DEBT_RECOVERY"),
    ISS_PAYMENT("ISS_PAYMENT");

    private final String value;

    Source(String value){ this.value = value; }
}
